image: python

stages:
- build
- test

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r requirements.txt

python35-lint:
  image: python:3.5
  stage: build
  script:
    - flake8 netblow
    - pycodestyle netblow
    - pydocstyle netblow

python34:
  image: python:3.4
  stage: test
  script: pytest -s -vv --cov=netblow tests/unit

python35:
  image: python:3.5
  stage: test
  script: pytest -s -vv --cov=netblow tests/unit

python36:
  image: python:3.6
  stage: test
  script: pytest -s -vv --cov=netblow tests/unit

python37:
  image: python:3.7-rc
  stage: test
  script: pytest -s -vv --cov=netblow tests/unit
