language: python

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install tox-travis
  - pip install coveralls

script:
  - TOXENV=lint tox
  - TOXENV=unit tox -- -s -vv --cov=netblow tests/unit

after_success:
  - coveralls
