version: '2.1'
services:
  netblow:
    image: quay.io/viniciusarcanjo/netblow:latest
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile.netblow.pypi
  master:
    image: quay.io/viniciusarcanjo/salt:2018.3.0
    privileged: true
    stdin_open: true
    tty: true
    command: 'salt-master'
    build:
      context: .
      dockerfile: ./Dockerfile.salt
    volumes:
      - /var/log
  minion:
    image: quay.io/viniciusarcanjo/salt:2018.3.0
    privileged: true
    stdin_open: true
    tty: true
    command: 'salt-minion'
    build:
      context: .
      dockerfile: ./Dockerfile.salt
    volumes:
      - /var/log
